import './globals.css'
import { Inter } from 'next/font/google'
import { LngProvider } from '@/contexts/LngContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <LngProvider>
        <body className={inter.className}>{children}</body>
      </LngProvider>
    </html>
  )
}
